#______                            ___________  _____ 
#| ___ \                          |_   _| ___ \/  __ \
#| |_/ /_   _ _ __   __ _  ___  ___ | | | |_/ /| /  \/
#| ___ \ | | | '_ \ / _` |/ _ \/ _ \| | |    / | |    
#| |_/ / |_| | | | | (_| |  __/  __/| |_| |\ \ | \__/\
#\____/ \__,_|_| |_|\__, |\___|\___\___/\_| \_| \____/
#                    __/ |                            
#                   |___/  By the almighty LaxWasHere                       
#
Bot:
    Nick: BungeeIRC
    Channel: '#Timelords'
    Network: irc.esper.net
    Port: 6667
    Password: Adsf123
Admins:
- LaxWasHere
- Yomama