#______                            ___________  _____ 
#| ___ \                          |_   _| ___ \/  __ \
#| |_/ /_   _ _ __   __ _  ___  ___ | | | |_/ /| /  \/
#| ___ \ | | | '_ \ / _` |/ _ \/ _ \| | |    / | |    
#| |_/ / |_| | | | | (_| |  __/  __/| |_| |\ \ | \__/\
#\____/ \__,_|_| |_|\__, |\___|\___\___/\_| \_| \____/
#                    __/ |                            
#                   |___/  By the almighty LaxWasHere                       
#
Bot:
    Nick:
    Channel:
    Network:
    Port:
    Password: